"""Model Explainability and Decision Breakdown Module.

Provides feature attribution and human-interpretable reasoning for
recommendations generated by the screening classification pipeline.
"""

from typing import Any, Dict, List, Optional
import pandas as pd
import numpy as np


def explain_prediction(
    pipeline: Any,
    candidate_df: pd.DataFrame,
    match_result: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """Generates human-readable decision factors and top feature contributions.
    
    Args:
        pipeline: Trained Scikit-Learn Pipeline with 'preprocessor' and 'classifier'.
        candidate_df: 1-row DataFrame of candidate features.
        match_result: Optional dictionary from match_resume_to_job.
        
    Returns:
        Dictionary containing positive factors, negative factors, and summary points.
    """
    reasons: List[str] = []
    
    row = candidate_df.iloc[0]
    exp = row.get("Experience (Years)", 0)
    skills = str(row.get("Skills", "")).split(",")
    skills = [s.strip() for s in skills if s.strip()]
    edu = row.get("Education", "B.Tech")
    cert = row.get("Certifications", "None")
    projects = row.get("Projects Count", 0)

    # 1. Job Role Fit Insights (if JD match result provided)
    if match_result:
        comp_score = match_result.get("composite_score", 0)
        missing = match_result.get("missing_skills", [])
        matched = match_result.get("matched_skills", [])

        if comp_score < 40.0:
            reasons.append(
                f"⚠️ Low Job Fit ({comp_score}%): Candidate is missing critical skills: {', '.join(missing[:4]) or 'Required competencies'}."
            )
        elif comp_score >= 70.0:
            reasons.append(
                f"✅ Strong Job Fit ({comp_score}%): Candidate matches core required skills ({', '.join(matched[:4])})."
            )
        else:
            reasons.append(
                f"ℹ️ Moderate Job Fit ({comp_score}%): Partial skill overlap with missing areas in {', '.join(missing[:3])}."
            )

    # 2. General Profile Heuristics
    if exp >= 3:
        reasons.append(f"Strong industry experience ({exp} years) boosts recommendation profile.")
    elif exp == 0:
        reasons.append("Entry-level/Fresher profile with 0 years of recorded experience.")
    else:
        reasons.append(f"Early-career experience profile ({exp} year(s)).")

    if len(skills) >= 5:
        reasons.append(f"Broad technical skill set identified ({len(skills)} verified technical skills).")
    elif len(skills) >= 2:
        reasons.append(f"Moderate technical coverage ({len(skills)} technical skills).")
    else:
        reasons.append("Limited technical keywords identified in profile.")

    if cert != "None":
        reasons.append(f"Verified domain certification: {cert}.")

    if projects >= 3:
        reasons.append(f"Solid portfolio of practical work ({projects} demonstrated projects).")

    # 3. Linear Model Coefficient Inspection (if available)
    feature_impacts: List[Dict[str, Any]] = []
    try:
        classifier = pipeline.named_steps.get("classifier")
        preprocessor = pipeline.named_steps.get("preprocessor")

        if classifier and preprocessor and hasattr(classifier, "coef_"):
            # Transform candidate row to feature vector
            x_vec = preprocessor.transform(candidate_df)
            if hasattr(x_vec, "toarray"):
                x_vec = x_vec.toarray()

            feature_names = preprocessor.get_feature_names_out()
            coefs = classifier.coef_[0]  # Binary classification weights

            # Compute contribution: feature_val * coefficient
            contributions = x_vec[0] * coefs
            active_indices = np.where(x_vec[0] != 0)[0]

            for idx in active_indices:
                name = feature_names[idx]
                clean_name = name.replace("skills_text__", "Skill: ").replace("categories__", "").replace("numbers__", "")
                val = contributions[idx]
                feature_impacts.append({
                    "feature": clean_name,
                    "impact": round(float(val), 3),
                    "type": "Positive" if val > 0 else "Negative"
                })

            feature_impacts.sort(key=lambda item: abs(item["impact"]), reverse=True)
    except Exception:
        pass

    return {
        "summary_reasons": reasons,
        "feature_contributions": feature_impacts[:8]
    }
